### ISSUE TITLE
Requirements: Database Setup

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#1]
Requirements for setting up the database connection within FreeTube

- All database logic should be stored with VueX (Adding to database, deleting from database, etc.)
- Each database should be in their own store
- The default database file location should be in `electron.remote.app.getPath('userData')`
- If FreeTube is used without Electron, it should default to a folder within the source folder
- The user should be allowed to manually set where their database is stored (Within the settings page)

**Comment by GiraffeKey** [comment]
I would recommend using a decentralized storage platform such as Blockstack or Solid. That way data can be saved to the cloud and users will have full control over their own data.

**Comment by GiraffeKey** [comment]
https://github.com/solid/solid-tutorial-intro

**Comment by PrestonN** [comment]
Closing as the database is already setup.
