### ISSUE TITLE
Storyboard images moving out of view

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube-Vue#101]
When you scroll through the timeline of a video and take a look at the storyboards, the images at the beginning and the end of the video move outside of the player screen and get partially blocked, because their rendering area is over.

![image](https://user-images.githubusercontent.com/34301369/91200606-a820eb00-e6ff-11ea-82d4-5adbdf3bcb1f.png)

The horizontal coordinates that the frame showing the images can move to must be clamped, in order to stop the frame from moving too far.

**Comment by PrestonN** [comment]
This would need to be fixed upstream.  The upstream repository is [here](https://github.com/chrisboustead/videojs-vtt-thumbnails), but it seems like the maintainer isn't very active.  I sent a PR a while back to him that still hasn't been looked at.  It might be worth maintaining a fork of it with these types of fixes.
