### ISSUE TITLE
Subtitles not showing up when video is first loaded.

### ISSUE THREAD

**Issue by Hiers** [FreeTubeApp/FreeTube-Vue#103]
Subtitles will only load after changing video format type.
![subtitles](https://user-images.githubusercontent.com/47784553/91303770-039eb780-e798-11ea-8bbc-202954c648ca.png)

**Comment by PrestonN** [comment]
I just pushed out a potential fix for this, could you please test and confirm that it's working as intended?

**Comment by PrestonN** [comment]
We've determined that the primary cause of this has something to do with slow / Tor connections. I'll revisit this when Tor functionality is finished so that I can have a better environment to work in.  Since this will be after the first release, I will be closing this issue.
