### ISSUE TITLE
Featured Channels not working

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube-Vue#104]
When going to the about page of a channel and trying to click on one of the featured channels it does not take you to the channel.

![image](https://user-images.githubusercontent.com/34301369/91348054-85680280-e7e3-11ea-8516-5e9786b3dc3d.png)

**Comment by PrestonN** [comment]
Yep. It doesn't do anything yet. This functionality will come along with subscriptions as I'll be using those components for a dual purpose.

**Comment by PrestonN** [comment]
This should be fixed now.  Closing.
