### ISSUE TITLE
Channel links in search results not working

### ISSUE THREAD

**Issue by Hiers** [FreeTubeApp/FreeTube-Vue#106]
Clicking on the channel link below a video in search results brings up a blank screen, with the window name becoming "undefined - FreeTube-Vue". It is worth noting that channels as their own bespoke search result, not just as part of the search result of a video, don't suffer this problem; and neither do any channel links in the Trending and Most Popular tabs.

**Comment by PrestonN** [comment]
I actually just fixed this about 10 minutes ago haha.  Update your app and it should be fixed.

**Comment by Hiers** [comment]
Oh oops. Thanks for the clairvoyant fix.
