### ISSUE TITLE
Uncaught TypeError: this.player.vttThumbnails is not a function

### ISSUE THREAD

**Issue by palaima** [FreeTubeApp/FreeTube-Vue#113]
Hey

Getting errors with `vttThumbnails` and `httpSourceSelector` any ideas what's happening here?

**Comment by PrestonN** [comment]
Are you running in dev (`npm run dev`)?  You might have to do another `npm install` as we forked the upstream package due to a lack of development.

If you're not running in dev, try updating to the latest release.

**Comment by palaima** [comment]
correct, i'm running in dev, will try

**Comment by palaima** [comment]
Indeed, reinstalling solved the issue, Ty
