### ISSUE TITLE
Use subscription list from legacy FreeTube

### ISSUE THREAD

**Issue by gtsop** [FreeTubeApp/FreeTube-Vue#114]
Is there a way to re-use the subscription list already present on my system for the legacy FreeTube application?

The use case is I want to start using this Vue version because a) it fixes some major problems for me b) to provide feedback and bug reports and c) contribute back. However since I make heavy use of the FreeTube app it would be great if I didn't have to manually setup my subscriptions again.

Also, this functionality would make for a good transitioning experience when this rewrite lands to mainstream. 

I understand the aspects of limited time, just want to understand if there is an existing solution to this and what the intentions are for the future.

**Comment by GilgusMaximus** [comment]
This will come. It was discussed in the Matrix channel already. He'll likely add a functionality to the old client to export it in the correct format or create some extra scripts, so that it can be imported easily into the new client. 

However for the moment that is not possible.

**Comment by GilgusMaximus** [comment]
So I created a command line application that can convert your old subscription file to the new format.
You can find it here.
Either you run the source code, or use one of the executables in the releases tab.
Hope it helps you :)
https://github.com/GilgusMaximus/freetube-subscription-converter

**Comment by gtsop** [comment]
> So I created a command line application that can convert your old subscription file to the new format.
> You can find it here.
> Either you run the source code, or use one of the executables in the releases tab.
> Hope it helps you :)
> https://github.com/GilgusMaximus/freetube-subscription-converter

Thank you so much! Will try it right away.

**Comment by gtsop** [comment]
Successfully ran the script. It puts all the subscriptions into a single profile, won't complain about it though since it's already very helpful. Thanks again!
