### ISSUE TITLE
Local API fallback from Dash format - Collection thread

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube-Vue#118]
Hello everyone.
So as I am the maintainer of the DASH manifest generation module, I'd like to gather all the videos where the local API with Dash format fails and falls back to legacy. 

So if you experience issues with the Dash format in the local API, or missing quality options (like no 720p or no 1080p if there is on the actual YouTube video), please post the video link in here, so that I can take a look at it and see why it fails.

If you do no have a Github account, and really do not want to create one, you can mention me in the Matrix chat as well.

Thanks for your cooperation :)

**Comment by Hiers** [comment]
https://www.youtube.com/watch?v=7vlt0lLzzYQ
This video falls back to the legacy format before you even click the video to start playing it.

**Comment by GilgusMaximus** [comment]
Okay. That is interesting. I just tested the video and for me it works fine. 
Did you go out and in again? 
That fixes the problems sometimes.

And to make it easier to debug in the future, it would be helpful if **everyone** that has a problem could go to the dashFiles/ folder and copy the contents of the file with the video id. For windows the path is `C:\Users\username\AppData\Roaming\FreeTube-Vue\dashFiles` and for Linux I was told it is `~/.config/Electron/dashFiles`.

Because there must be an error in the file, which causes this to happen, or there is a loading error, so that the code tries to load the file before it is ready.

**Comment by Hiers** [comment]
Historically, changing back to dash format hasn't helped. When it doesn't work it either auto-changes to legacy when I change to dash, or it loads indefinitely. This time again, changing from and back to dash didn't help.
Here is my dash file for the video I posted: 

[7vlt0lLzzYQ.xml.zip](https://github.com/FreeTubeApp/FreeTube-Vue/files/5179595/7vlt0lLzzYQ.xml.zip)

**Comment by Hiers** [comment]
Addendum: immediately after I posted this, it worked with dash, then I tried again and it stopped working again. I couldn't tell you why this happened.

**Comment by GilgusMaximus** [comment]
Yeah. I am not sure either. Maybe some loading issue with the file.
I also thought about a problem with the video URL in the dash manifest. But the other provided formats didn't help either.
Only made things worse.

Not much I can do at this point, as the only thing left to test is to add a delay to the video page and wait for all files to securely load. However that is of course bad for performance.

**Comment by GilgusMaximus** [comment]
Okay I'm going to close the issue, as there is currently not much I can do about Dash formats not playing.
The dash file is generated correctly.
Either there is a problem with race conditions or the videojs media player sometimes has a problem with the file, which goes away after some time and many retries.

If the problem comes up a lot after the release I might reopen this thread.
