### ISSUE TITLE
TypeError: Cannot read property 'simpleText' of undefined

### ISSUE THREAD

**Issue by uuuu1234** [FreeTubeApp/FreeTube-Vue#120]
I get the error text 'TypeError: Cannot read property 'simpleText' of undefined' when starting up the application (v0.8.0 Alpha), but everything seem to work well.

**Comment by GilgusMaximus** [comment]
Which language are you using?
If you are not using one of the languages that are 100% translated (or English), then there might be non translated words, which could lead to this error.

With English and German I am not getting this error.

**Comment by uuuu1234** [comment]
I do use English (US), but I also must say that I haven't encountered the error again.

**Comment by PrestonN** [comment]
The only occurrence of the `simpleText` variable within the entire project is with captions in a video.  Please provide an example video where you are experiencing this issue and we can take a closer look at it.

**Comment by GilgusMaximus** [comment]
Coudl this relate to #103 ?

**Comment by PrestonN** [comment]
I will be closing this issue since we haven't had an update in a while.  If you encounter the issue again, feel free to create a new issue.
