### ISSUE TITLE
Screen freezes in acer nitro 5

### ISSUE THREAD

**Issue by Spritan** [FreeTubeApp/FreeTube-Vue#124]

**Comment by Spritan** [comment]
Its a problem generally which occurs when hardware acceleration is turned on in chromium based browsers and not under any other circumstances. But is had to deal with it many time with current build in actions . Please check what can be done. On windows 10 latest version.

**Comment by PrestonN** [comment]
This seems to be extremely device specific.  If it has something to do with hardware acceleration then I'm not too sure what the solution would be.  It is something I'd rather not disable as well.  I'm open to ideas but unfortunately nothing comes to mind.

**Comment by Spritan** [comment]
If harware acceleration is used in the application than providing an option to off it may be usefull. I don't possess much idea regarding this matter.

**Comment by PrestonN** [comment]
I've created a build [here](https://github.com/PrestonN/FreeTube-Vue/actions/runs/246834006) that disables hardware acceleration.  You may need to wait a few minutes in order for the builds to be complete.  If these builds work for you, then I will consider adding a toggle to disable hardware acceleration.  Let me know how they work.

**Comment by Spritan** [comment]
I have installed and started using this build if i encounter the problem again i will let you know.

**Comment by Spritan** [comment]
this build seems to be working fine without even a single occurrence of the bug.

**Comment by PrestonN** [comment]
Since this seems to be working for you, I will make plans to include a toggle to disable hardware acceleration in a future release.  Having said that, I will likely not me working on this until after the first release.  Because of this, I will be closing the issue here.  Feel free to create a new issue over on the main repo once the first release has passed to remind me to create a new toggle.

**Comment by Spritan** [comment]
ok
