### ISSUE TITLE
Mini-Player: Error problem

### ISSUE THREAD

**Issue by Spritan** [FreeTubeApp/FreeTube-Vue#126]
If i active mini-player and go to settings and again click back-to-video-player the mini player goes off but viseo player don't open also audio plays in background with no open to off it and if play a new video both their audio can be heard.

**Comment by PrestonN** [comment]
I'll look into this.  I can't guarantee that this will be fixed in time however.

**Comment by Spritan** [comment]
ok no prob an eventual fix is enough i just brought it up to keep the issue in sight.

**Comment by PrestonN** [comment]
This should be fixed now.
