### ISSUE TITLE
Channel links in featured channels section in about page don't work

### ISSUE THREAD

**Issue by Spritan** [FreeTubeApp/FreeTube-Vue#128]
The option are shown but don't work when clicked

**Comment by GilgusMaximus** [comment]
Mentioned in #104 .
However it did not come along with what has been done with the subscriptions yet.

**Comment by Spritan** [comment]
Oh i didn't notice your issue.

**Comment by PrestonN** [comment]
Yep, this is a duplicate.  Will have this fixed soon.  Closing for now.
