### ISSUE TITLE
Copy/pasting YouTube URLs in the nav bar ignores some query parameters

### ISSUE THREAD

**Issue by VioletRose** [FreeTubeApp/FreeTube-Vue#133]
When pasting a YouTube URL containing query parameters specifying a start time or playlist, those parameters are ignored. The video will play from the start and no playlist is visible.

The parameters which are ignored include `t`, `list`, and likely `index` (which can't be confirmed until `list` is supported).

**Comment by PrestonN** [comment]
I will work on fixing this after the first release.  You're welcome to create a new issue back at the main repo once the release has passed.
