### ISSUE TITLE
Reload Video

### ISSUE THREAD

**Issue by qgiguiere** [FreeTubeApp/FreeTube-Vue#135]
If I leave a video paused for a few hours I get a network error when I resume the video like the one in this screenshot. 
![image](https://user-images.githubusercontent.com/36967180/93142035-7c5fa800-f6a2-11ea-8205-4c2b8270a6b6.png)

It has also happened a couple of times while I was watching a video. In order to keep watching I have to navigate away from the page and come back to it. I also have to find where I was in the video before the error. Would it be possible to include a button to reload the video to avoid having to leave the page and come back? It's not a big deal but it would be a nice addition.

**Comment by PrestonN** [comment]
I'll consider adding this after the initial release.  At that point, we'll be back to the main repo for issues, so you're welcome to make a new issue over there once the rewrite has been officially released.
