### ISSUE TITLE
Videos on subscribed channels get switched when changing between channels

### ISSUE THREAD

**Issue by qgiguiere** [FreeTubeApp/FreeTube-Vue#136]
If you are on the homepage of a subscribed channel and then go to the homepage of a different subscribed channel, sometimes the videos for one channel get displayed on the homepage of the other channel and vice versa.
![image](https://user-images.githubusercontent.com/36967180/93146476-298aee00-f6ac-11ea-9f91-00adfd9febbe.png)
![image](https://user-images.githubusercontent.com/36967180/93146496-3a3b6400-f6ac-11ea-927b-036ed34809f5.png)
The videos displayed on the first picture belong to the channel displayed on the second picture and vice versa.

**Comment by PrestonN** [comment]
I just pushed up a potential fix for this.  Please let me know if you still experience this issue or not.

**Comment by PrestonN** [comment]
I haven't been given an update so I'll go ahead and close this as fixed.  If the issue comes up again feel free to re-open.
