### ISSUE TITLE
Yellow Border Remains When Clicking Player Elements

### ISSUE THREAD

**Issue by MetalNeo** [FreeTubeApp/FreeTube-Vue#137]
When clicking on different elements in the video player, a yellow border is drawn around the element. This border can be distracting, particularly when watching videos in fullscreen. It would be nice if the yellow border disappeared after a few seconds or if it could be disabled entirely.

On a related note, it would also be nice to be able to force the spacebar shortcut to stick to the pause/play button instead of the last selected element.

**Comment by PrestonN** [comment]
We chatted about this in our Matrix server before and the agreement was that the outlines are required for accessibility reasons when you're attempting to tab around the app.  Asking again in the chat it was agreed that we can disable these when the user is clicking around and enable them when Tab is used.  I have pushed out a fix and should satisfy all parties.
