### ISSUE TITLE
Shortcut to mark videos as watched

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube-Vue#140]
For the moment we currently need to use the 3-points menu below a video in order to mark it as watched. 
There should be a quicker way to do it with a button on the thumbnail or with a shortcut (e.g. ALT + LeftClick on the video).

Here is a user script that does that (uses a shortcut) : https://greasyfork.org/scripts/30261-mark-watched-youtube-videos/

**Comment by PrestonN** [comment]
I like this idea, I really do.  I don't believe I'll be able to work on it before release however.  Once our first release has come and passed, please make a new issue back on the main repo and we'll track progress there.  Since this won't be worked on beforehand, I'll be closing this issue here.
