### ISSUE TITLE
Playlist: Freetube trying to open deleted video

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#148]
Try to open deleted video from playlist. Freetube trying to open movie but without success. Should be info about that, but app shouldn't trying to open movie.

**Comment by PrestonN** [comment]
I've removed private and deleted videos from the watch playlist which should prevent this.  Let me know if this comes up again.

**Comment by pawlosck** [comment]
Looks well. In next release you can add switch to hide these movies everywhere. For example, when you open playlist (before start playing). I will report it later.

**Comment by PrestonN** [comment]
I'm going to keep it how it is as I believe it's important that users are aware that there used to be a video in that playlist but it is now deleted or privated.  It makes sense to hide it if you're playing the playlists but there isn't a huge reason to hide it when you're just viewing a playlist.  I think it's fine the way it is.

**Comment by pawlosck** [comment]
Yes, I agree, so I sugest to add switch, to hide temporary. For example: Playlist contains a lot of movies (500-1000) and most of movies are deleted. I can hide wrong movies to fast look only available movies. That's all.
