### ISSUE TITLE
Some video thumbnails don't appear in video player

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#149]
1. Open playlist with deleted movies.
2. Try to open any movies (not deleted)
3. You will see in player picture, which looks like deleted movie.
4. When you push "play icon" in player, then movie start normally.

Auto play is off

**Comment by PrestonN** [comment]
Your issue has nothing to do with playlists.  I've renamed the issue for you.  I will try to look at this soon.

**Comment by PrestonN** [comment]
This has been fixed
