### ISSUE TITLE
SponsorBlock API Integration

### ISSUE THREAD

**Issue by digg33** [FreeTubeApp/FreeTube-Vue#15]
From the Github repo, ajayyy/SponsorBlock:
SponsorBlock is an extension that will skip over sponsored segments of YouTube videos.

The service also comes with an API and publically available database, so I think
it might be worth a look as a possible future enhancement.

**Comment by PrestonN** [comment]
This is something that I'm wanting to look into.  It'll likely be a while before I implement it but it's planned within the rewrite.

**Comment by digg33** [comment]
Would you consider giving this an "enhancement" tag?

**Comment by PrestonN** [comment]
There you go :)

**Comment by PrestonN** [comment]
This feature will likely not be included in the initial release.  Because of this, I will be closing this issue and we can continue the discussion in the main repo once the initial release has passed.  I know that there is already an issue about this feature over there.
