### ISSUE TITLE
Video should auto play in playlist event thought selected auto play videos off

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#153]
I have set settings like this:
- Auto play videos -> off
- Autoplay playlist -> off
- play next video - on

When I open movie page or playlist page, then movie is not starting play -> OK
When I start playing playlist, movie is switching to next video, but not starting playing -> BUG

**Comment by PrestonN** [comment]
I would say this is working as intended because you disabled Autoplay in your settings.  If you want the video to play when the next video is available, then you should enable Autoplay in your settings.

**Comment by pawlosck** [comment]
Look at youtube. I think youtube behavior is more intuitive.
Option "play next video" should including Auto play videos -> on for playlists, or option "Auto play videos" should be splitted.
"Auto play single video" and "Auto play videos in playlists".
Option "play next video" is not make sense, when video is not auto playing. Try to listen to playlist with music and after every song you have to press play.

 What do you think?
