### ISSUE TITLE
Updating a profile removes subscriptions

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube-Vue#156]
When you click the "Update profile" button, all subscriptions assigned to this profile are removed.

![video](https://user-images.githubusercontent.com/17936055/93996002-fc1bff80-fd91-11ea-996a-228808d52915.gif)

**Comment by GilgusMaximus** [comment]
When did you download the build?
In my version, from the 22nd it does not happen.

**Comment by PrestonN** [comment]
I can confirm that this is a bug.

Steps to reproduce:

1. Select a profile
2. Add / delete channels from profile
3. Click on "Update Profile"

The channels you just added / deleted will then be undone.  I have an idea on how to fix this and will try to get a fix pushed out soon.

**Comment by PrestonN** [comment]
This should now be fixed
