### ISSUE TITLE
Text size of some parts of the UI

### ISSUE THREAD

**Issue by linuxgirl22** [FreeTubeApp/FreeTube-Vue#163]
Hello :-)
I literally just saw a comment on Reddit where someone said they'd been using the new Vue for a while, found it on the AUR, and it's amazing! Thanks for all your work with this. Everything looks very colourful and clean, and it loads so fast! The only issue I have is that some parts of the UI text are uncomfortable to try to read. The comments and text along the right-side bar, I wouldn't be able to manage (have been using Liferea and able to freely zoom that). The settings text is a little difficult. Titles of videos are an excellent text size, but the names/views/times underneath are too small to comfortably read. Not sure if Vue is made for HiDPI monitors? I have no idea what's involved in this, but is there any way there can be a custom setting to zoom up the interface text?

If I've missed a setting, apologies, but I've looked everywhere, bar setting up a profile, and can't see any settings for text size.

**Comment by PrestonN** [comment]
Hello!

The size of the UI can be increased by using `Ctrl + Shift + =` on your keyboard.  It doesn't seem like it will save this setting upon restart however.  I don't own a 4k monitor to test with so I'm not too aware of any issues that might show up with higher res monitors like that.  I can add a setting to adjust the UI scaling once we're past the first release.  Feel free to make a new issue over on the main FreeTube repository about it once the first release has passed.

Thanks!

**Comment by linuxgirl22** [comment]
Hi! And thank you very much for the shortcut; that's helped with the main display really well, and wonderful news that UI scaling can be adjusted ... I'll make sure to create a new issue. Sorry, I didn't make it clear that I'm on a trusty 1080 monitor too. Thanks so much again, and for you awesome work on this! :-)
