### ISSUE TITLE
Freetube not responding when user open specific movie (live stream scheduled in the future)

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#164]
Try to open this movie https://www.youtube.com/watch?v=PYTkcZJmG6s in Freetube.
Freetube not responding. I can't go back to subscription list, open any movie or switch to channel. There is only working searching field.

This issue can be reproduced, when you open this stream immediately after open Freetube. You can't watch other movie before.

**Comment by PrestonN** [comment]
This should be fixed now.
