### ISSUE TITLE
There are no info about date for scheduled stream

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#165]
Try to find scheduled live stream in subscription list. There are no info about date and time when live stream will be started.
Based on the thumbnails, user thinks that streaming is now. There is text "LIVE" and number of watching people.

**Comment by PrestonN** [comment]
I'm likely not going to be fixing this until after the first release.  This will take some changes to the backend scraper in order to include which I don't think I'll have time to work on.  I can look at this again at a later point.
