### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#166]
Every time (since about two days), when I open Freetube, I see three messages "TypeError: Cannot read property 'text' of undefined".

I supposed, that this issue can be connected with https://github.com/FreeTubeApp/FreeTube-Vue/issues/165

**Comment by PrestonN** [comment]
This was a different issue actually.  This should be fixed now.  You'll have to do a `npm install` to have it properly fixed.
