### ISSUE TITLE
TypeError: Cannot read property 'reverse' of undefined - Stream can't be opened (right now)

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#167]
Try to open stream https://www.youtube.com/watch?v=PYTkcZJmG6s
There is message TypeError: Cannot read property 'reverse' of undefined
and page with stream can't be opened.

If I remember well, there was similar issue with premiere.

**Comment by PrestonN** [comment]
This has been fixed.  It wasn't detecting the video as a live video and couldn't grab the video properly because of it.
