### ISSUE TITLE
Duplicate translation (Portuguese)

### ISSUE THREAD

**Issue by syncng** [FreeTubeApp/FreeTube-Vue#171]
[pt.yaml](https://github.com/FreeTubeApp/FreeTube-Vue/blob/72461b4/static/locales/pt.yaml) and [pt-PT.yaml](https://github.com/FreeTubeApp/FreeTube-Vue/blob/72461b4/static/locales/pt-PT.yaml)
How did this even happen?

**Comment by RickyM7** [comment]
Não seria o português de Portugal (Pt-PT) e o português do Brasil (Pt)?

**Comment by syncng** [comment]
If you took one look at the locals folder, you'd see that [pt-BR.yaml](https://github.com/FreeTubeApp/FreeTube-Vue/blob/72461b4/static/locales/pt-BR.yaml) also exists -_-

**Comment by RickyM7** [comment]
@syncng Yes, I just saw it.  Apparently it is duplicated, but I'm not sure.

**Comment by PrestonN** [comment]
This is something that gets automatically created when someone makes a new language within Weblate.  Even though different countries speak the same language, each country might have regional differences that other countries don't take into account.  An example of this would be UK English versus US English, which also exists in the project.

There's nothing wrong with duplicates as long as there are valid reasons for having the different variants.

Having said that, I have been told that the pt.yaml is a carbon copy of the pt-BR.yaml and can possibly be deleted, so I might do that here soon.
