### ISSUE TITLE
Movie is unavailable in your country

### ISSUE THREAD

**Issue by pawlosck** [FreeTubeApp/FreeTube-Vue#173]
I tried to listen to this song https://www.youtube.com/watch?v=otSGO77yLv8
and Freeetube show me "TypeError: Cannot read property 'formats' of undefined".
When I opened this movie in youtube, I saw message, that this movie is not available in my country.
This error stops playlist, because movie can't be opened.

**Comment by PrestonN** [comment]
This should be fixed in #174
