### ISSUE TITLE
Video UI Selection Bug

### ISSUE THREAD

**Issue by arthurrasmusson** [FreeTubeApp/FreeTube-Vue#18]
On FreeTube's video player there are a number of pixels which when hovered over with the mouse cause the playback UI to loop the open and close animation.

Here is an example of the looping animation:
![out](https://user-images.githubusercontent.com/47877520/77828363-54c75400-70f1-11ea-802c-87643c2ae7de.gif)

Suggestion:
While at Oculus Connect John Carmack dedicated part of his time to an "app review" panel to allow developers to receive his feedback on their Oculus apps. A portion of the talk dealt with 2D UX principles and in one case an app had a very similar UI bug. His suggestion was the best way to fix this is to have a small area where if you swipe over from one button into another one adjacent to it the first few pixels (for example 3 pixels) does not transition the selection. So this could be considered a sort of "null space" for selection changes.

**Comment by PrestonN** [comment]
Should be fixed with #30
