### ISSUE TITLE
Fullscreening a video disables keyboard shortcuts

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#19]
Fullscreening a video through click prevents the keyboard shortcuts from working.  An extra click on the video itself is needed in order for the shortcuts to work again.

**Comment by kylejwatson** [comment]
How should the space bar key shortcut be handled? The current behaviour in videojs is to fire the 'click ' event on the button that currently has focus, which will be the fullscreen button after it's pressed.

There is a few routes to take with this:

1. Disable 'space' clicking on focused elements, this reduces accessibility but means that the spacebar will always play/pause a video if any video element is focussed
2. Enable leave the current functionality of space 'clicking' focused buttons but also enable it to play/pause, eg if the fullscreen button is focused and a user presses space it will toggle fullscreen and toggle play/pause
3. Disable 'space' clicking just for fullscreen toggle.
4. Leave the 'space' clicking functionality and only enable other shortcuts when a button is focused.

I'm going to make a PR for option number 4 but let me know what you think.
