### ISSUE TITLE
Video Player logic: add possibility to change speed to faster than 2x

### ISSUE THREAD

**Issue by bergben** [FreeTubeApp/FreeTube-Vue#22]
It would be really amazing if it is possible to change the speed per-some keyboard shortcut in steps of 0.1. 
For some videos speeding up to 2x the speed simply isn't enough. 

Pragmatic solution would be to include 2.25 and 2.5 in the current choices

I would absolutely love this feature

**Comment by PrestonN** [comment]
It's extremely trivial to add more playback rates as you can see from [this](https://github.com/FreeTubeApp/FreeTube-Vue/blob/320c305949770e481ad6663fd461d4513ff5626a/src/renderer/components/ft-video-player/ft-video-player.js#L81) code.  You'll also notice that I have already added playback options up to 3x.

By itself, adding different steps would be just as easy, though I don't think I'd be too keen on changing the steps as a default at least.  I would rather have a settings option that "unlocks" the playback steps to allow for more control.  At that point I would allow the player itself to show more options.  This would be a little bit of extra work of course, though I don't think it would take too long to do.

**Comment by bergben** [comment]
Good idea! :)

**Comment by PrestonN** [comment]
I will be closing this issue as we are nearing the initial release of the rewrite.  Please feel free to remake this issue on the main repo once the initial release has passed.
