### ISSUE TITLE
Randomize invidious instances

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube-Vue#23]
(I figure here is better place to suggest than FreeTubeApp/FreeTube as it's probably getting more active development)

It would be nice feature if FreeTube-Vue were able to randomize which invidious instance it used on start up.   This would help spread the load across volunteer run instances rather than one shipped with FreeTube by default.

Maybe sourcing the list at startup from an `indivious.txt` text file in the github repo.   Perhaps if invidious devs could be convinced the list could be on their git hub so it's more likely to be cleaned when a site becomes inactive.

Of course not everyone would want this, so including an opt out so you can limit your self to one  invidious server

**Comment by PrestonN** [comment]
This was mentioned in our Matrix server, though I believe @cloudr3cer is wanting to work on this feature, so it's planned.

**Comment by cloudrac3r** [comment]
Correct. I don't know when I get around to it, since I'm contributing to this is my spare time amidst many other obligations, but I'm sure I can do it before the rewrite is finished :D

**Comment by PrestonN** [comment]
This feature will not be worked on for the initial release.  Since we are nearing the initial release, I will go ahead and close this issue.  Feel free to make a new issue in the main repo once the initial release has passed.

**Comment by grrrrr** [comment]
@PrestonN that's fair,  especial given the flux invidious is going through at the moment.
