### ISSUE TITLE
Alt arrow keys to move in history

### ISSUE THREAD

**Issue by B0pol** [FreeTubeApp/FreeTube-Vue#24]
You have added this buttons and it's really great, I appreciate it. ![image](https://user-images.githubusercontent.com/58657617/83349377-c5c6fa00-a334-11ea-98ff-9a53ba6c5297.png)
That would be even greater to support alt+left arrow key to go backwards, and alt+right arrow key to go forward in history, like firefox or chrome do

**Comment by PrestonN** [comment]
Well that's easy.  Should be done in  e68bc0d
