### ISSUE TITLE
The window size is reset after restart 

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube-Vue#25]
It looks like when I change the size of the app window and close the app and then restart it, the size is reset to the default one.

**Comment by PrestonN** [comment]
This is something that I simply haven't gotten to just yet in the rewrite.  It's of course something that I will be adding before it's finished.

**Comment by Spritan** [comment]
also ctrl- reduces the size but i am unable to increas if i over did it unles i restart it.

**Comment by T-vK** [comment]
[Ctrl]+[0] resets your zoom
[Ctrl]+[-] zooms out
[Ctrl]+[Shift]+[+] zooms in
(That's at least how it works on a qwertz layout.)
You can also do it without shortcuts, using the view menu which should pop up when pressing [alt]:
![image](https://user-images.githubusercontent.com/11368523/92702005-f74a5b00-f350-11ea-9c55-16636eee0a1b.png)

**Comment by Spritan** [comment]
Oh thanks for the reply

**Comment by T-vK** [comment]
No problem, but nevertheless, you should consider opening a separate issue because I see zooming still has a lot of problems:
- [Ctrl]+[Mousewheel] doesnt work
- [Ctrl]+[+] doesn't work
- [Ctrl]+[Shift]+[+] is unintuitive
- Zooming shortcuts don't work at all while the video player is in focus

**Comment by Spritan** [comment]
ok i will surely do it but first lets wait till 1.0 some visible features like playlist are done.

**Comment by PrestonN** [comment]
This has been added.  Closing
