### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by KizunaH** [FreeTubeApp/FreeTube-Vue#27]

**Comment by PrestonN** [comment]
Localization is still something that I want to do.  I do have Weblate available and ready though I simply haven't had time to create the proper file needed to allow everyone to get started with making translations.  If anyone is interested in helping me create this, then please let me know and I can guide you in the right direction.  Doing this does not require any programming experience and is simply busy work to compile a file with all of the strings within the app.

**Comment by Archive5** [comment]
@PrestonN crowdin free for public projects so you can save some expense while that is non profit. You can scroll pricing page to see the comparison.

**Comment by Archive5** [comment]
> Weblate, If anyone is interested in helping me create this

I opened this FR then i am able to do that however may take bit time.

**Comment by PrestonN** [comment]
Localization is finally ongoing so this issue isn't needed any more.  Going to close this issue now.
