### ISSUE TITLE
Can't install under windows 10

### ISSUE THREAD

**Issue by 4ifi** [FreeTubeApp/FreeTube-Vue#39]
PS C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master> ..\npm.cmd install
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\vuex-a0459cc3\dist\logger.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\vuex-a0459cc3\dist\logger.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\vuex-a0459cc3\dist\vuex.common.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\client\utils\log.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\lib\utils\normalizeOptions.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\bin\options.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\client\overlay.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\lib\utils\processOptions.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\client\utils\reloadApp.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\lib\utils\routes.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\lib\utils\runBonjour.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\lib\utils\runOpen.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\webpack-dev-server-ee61c8d0\client\utils\sendMessage.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\vue-devtools-e343f877\vender\icons\128-beta.png'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\vue-devtools-e343f877\vender\icons\128-gray.png'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\typescript-764df867\loc\lcl\CSY\Targets\ProjectItemsSchema.xaml.lcl'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\typescript-764df867\loc\lcl\CSY\Targets\TypeScriptCompile.xaml.lcl'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master\node_modules\.staging\typescript-764df867\loc\lcl\CSY\Targets\TypeScriptProjectProperties.xaml.lcl'
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/FreeTubeApp/yt-channel-info.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-06-26T06_37_11_129Z-debug.log
PS C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master>

**Comment by 4ifi** [comment]
[2020-06-26T06_37_11_129Z-debug.log](https://github.com/FreeTubeApp/FreeTube-Vue/files/4835464/2020-06-26T06_37_11_129Z-debug.log)

**Comment by 4ifi** [comment]
PS C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master> ../npm run dev
npm WARN lifecycle npm is using C:\Users\Admin\Documents\node-v14.4.0-win-x64\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> freetube-vue@0.8.0 dev C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master
> run-s rebuild:electron dev-runner

"run-s" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freetube-vue@0.8.0 dev: `run-s rebuild:electron dev-runner`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freetube-vue@0.8.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-06-26T06_54_54_833Z-debug.log
PS C:\Users\Admin\Documents\node-v14.4.0-win-x64\FreeTube-Vue-master>

**Comment by 4ifi** [comment]
[2020-06-26T06_54_54_833Z-debug.log](https://github.com/FreeTubeApp/FreeTube-Vue/files/4835473/2020-06-26T06_54_54_833Z-debug.log)

**Comment by PrestonN** [comment]
This error seems to be based on your Node installation and not anything to do with FreeTube.  I would recommend trying to fix your Node installation or simply installing one of the automated builds over in the [Actions](https://github.com/FreeTubeApp/FreeTube-Vue/actions) tab.

For solving your Node issues, this is the part of the error message you want to use when you search for solutions.

`npm is using C:\Users\Admin\Documents\node-v14.4.0-win-x64\node.exe but there is no node binary in the current PATH`
