### ISSUE TITLE
Enhancement: (Auto) Download / Cache

### ISSUE THREAD

**Issue by T-vK** [FreeTubeApp/FreeTube-Vue#42]
From what I understand there are already plans to implement push notifications. It would be nice to have an option to also automatically download or cache new videos automatically once they are detected.

In the past, I've used a customized version of [youtube-dl-subscriptions](https://github.com/mewfree/youtube-dl-subscriptions) to do this. 

It would also be nice to have a download button in general. I think youtube-dl would be a very handy library to use for this as it can handle format conversion, merging of video and audio streams etc automatically. So you could even offer an option to "Download as MP3".

Maybe we could also use this to get videos to play in 4k (which was a problem if I recall correctly). youtube-dl has no problems with 4k I think.

**Comment by PrestonN** [comment]
This sort of functionality might be something to save for a possible "companion" server with FreeTube.  It's something I've been thinking of possible creating but it's kinda low priority at this point.  If I added this functionality within FreeTube itself, then it would only run when the app is running, which could possibly miss videos or use all of your bandwidth the moment the app is opened.

For a companion server, I'd imagine a headless app that would run constantly checking for subscriptions and download those videos as they come in.  This server could also handle push notifications by integrating with something like Gotify.  I've been having a hard time justifying the creation of something like this but if we can get a big enough feature set then I'd be willing to put a more serious look into it.

**Comment by T-vK** [comment]
I think you were talking about having the UI and the backend of FreeTube separated before. Would that companion server be another separate thing or would it be part of the backend server? 
It would be nice to have another issue describing how exactly the NewPipe components should be split in the future.

The auto-download should definitely have an option to limit the download speed. I used to do this with youtube-dl which has the `--limit-rate` flag to do so.

**Comment by PrestonN** [comment]
This is something that I won't be focusing on for the initial release.  Please feel free to create a new issue over on the main repo once the initial release has passed.
