### ISSUE TITLE
Enhancement: Filter for videos in subscription feed

### ISSUE THREAD

**Issue by T-vK** [FreeTubeApp/FreeTube-Vue#43]
I would like to see an option to filter out videos from specific channels containing certain keywords.
For example, let's say a channel uploads podcasts once a week and during the week it uploads small clips from that podcast.

Video 1: "Podcast 137"
Video 2: "Podcast 137 Clip 1"
Video 3: "Podcast 137 Clip 2"
Video 4: "Podcast 138"
Video 5: "Podcast 138 Clip 1"

It would be nice to be able to define a filter like:
`video.channel == "foo" && video.title.regex(/Clip \d+/)`
to filter out all videos from channel "foo" where the video title matches the given regex.
So you would end up only seeing those in your feed:

Video 1: "Podcast 137"
Video 4: "Podcast 138"

**Comment by PrestonN** [comment]
This is something that I won't be focusing on in the initial release.  Please feel free to create a new issue in the main repo once the initial release has passed.
