### ISSUE TITLE
Release portable version for freetube-vue

### ISSUE THREAD

**Issue by KizunaH** [FreeTubeApp/FreeTube-Vue#49]
This must be similar telegram portable. place the executable and run. it creates data folder, logs, updater on same location also update automatically.
https://desktop.telegram.org/
https://telegram.org/dl/desktop/win_portable

I aware volunteer contributor release portable version for old freetube.

**Comment by PrestonN** [comment]
I'll support any option that can be done automatically through the CI.

Since electron-builder seems to support a portable version, I see no reason why I can't publish builds of one.  Give me a day or so and I can get it up and running.

**Comment by PrestonN** [comment]
I've updated the CI tool to start uploading Windows Portable releases.  I haven't tested these so please let me know it these work the way you expect them to.  You can download a Windows Portable build through the actions tab and clicking on the latest build with the green check mark.

**Comment by KizunaH** [comment]
@PrestonN Thank you. Now we can use your every commits ;)

Few things.
1. There're two portable builds in github actions. `freetube-vue-0.8.0-win-x64-portable` `freetube-vue-0.8.0-portable-x64.exe`
Recently tested `freetube-vue-0.8.0-win-x64-portable`(executable) and i noticed it create folders on `C:\Users\Account\AppData\ Roaming\FreeTube-Vue` then is it possible to keep that data folders on same location eg: if ran it on `C:\Users\Portable` folder
2. Can you add update channels to freetube-app then we don't need to come to repository for download often.
Update channels: Release(most stable), Beta, Nightly (your commits builds also add skip this build option)
Additional: Display changelog within app for stable and beta builds.
(Nightly channel may have builds frequently and we can test and report bugs easily if has built-in automatic download and install feature) however you dont need to spend from your pocket, while build files available on action then make a way to reach the app. you may also able to try github alternative's CI/CD or other free service if difficult to deal with actions for that purpose.

**Comment by KizunaH** [comment]
Okey and i noticed one more problem.
freetube-vue-0.8.0-win-x64-portable(executable)
>Recently tested freetube-vue-0.8.0-win-x64-portable(executable) and i noticed it create folders on C:\Users\Account\AppData\ Roaming\FreeTube-Vue then is it possible to keep that data folders on same location eg: if ran it on C:\Users\Portable folder

>I plan on allowing you to change where data is stored in the future but for now it can't be changed within the app

I think it's not necessary to offer additional options for users to select custom data storage locations. since portable, i'm not prefer see it create folders, files on somewhere else on machine. For installer (default setup) you can follow the common method same as other softwares then people can pick a one.

Another problem. the .exe type portable version extract all files to separate temp folder `C:\Users\Account\AppData\Local\Temp \1fOA3ZPYNQVlIKgycCZmhRHxxHL` then i have to allow outbound for that application too through windows firewall (wfc)

However you need to bring that two folders to the same location that the executable has.
`C:\Users\Account\AppData\ Roaming\FreeTube-Vue`
`C:\Users\Account\AppData\Local\Temp\1fOA3ZPYNQVlIKgycCZmhRHxxHL`

Thank you again. ^_^
