### ISSUE TITLE
Requirements: ft-video-player component

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#5]
Requirements for the FreeTube video player component

I have not completely decided yet on what video player I want to use.  FreeTube currently uses MediaElement.js and it has been working fine.  The problem with it is that some things work odd or I had to implement certain features myself.  I'll start with trying out Video.js since it has similar features and seems to be more stable.  All other video players that I've found has one reason or another for not being desirable for use with FreeTube. Either one we use will have the same requirements.

If we decide to stick with MediaElement.js, certain changes will have to be ported over to upstream so that they can be used within the NPM package.  If we can't port them to upstream, we will have support our own fork.

Requirement for Implementation:

- Component should support .mp4, .mpd (Dash manifest file), and .hls (Live video feed)
- Component should support .vtt (Used for captions) files
- Component should support changing the video quality (Especially for Dash and live feeds)
- Component should show 60fps quality options if available.
- Component should support the various keyboard shortcuts.  [List is here](https://github.com/FreeTubeApp/FreeTube/wiki/Keyboard-Shortcuts) (The video players should have some of these enabled by default)
- Component should have support for enabling markers (I want to use these for a future download video / audio feature, so this is important)
- Component should hide the mouse cursor when the cursor has been in front of the video for more than a couple of seconds.
- Component should support showing video thumbnails across the timeline.
- Player speed should max at 3x and go as low as 0.25x.

**Comment by chakflying** [comment]
Is there a particular reason why the local API does not support higher resolution than 720p? I quickly browsed around the code and don't quite see the reason of this, and video.js should support the DASH format?

**Comment by PrestonN** [comment]
The simple reason is because the local API doesn't provide a proper DASH file / url to use in order for 1080p+ videos to play.  Invidious can currently generate this file and FreeTube will use that.  In order for the local API to support 1080p+ videos, we'll have to generate this DASH file within FreeTube and then attempt to play that file.  It should be possible to do but I simply haven't looked into it.

**Comment by PrestonN** [comment]
Closing as this is finished.  There are still a few small issues though at this point they will be better suited for new issues.
