### ISSUE TITLE
[Question] Enhancement to freetube

### ISSUE THREAD

**Issue by Rru247** [FreeTubeApp/FreeTube-Vue#51]
Even after proxied through invidious then i see connectivity for below domains.
`youtube-ui.l.google.com`
Isn't it possible to prevent use these domains and relay on invidious?

`i.ytimg.com`
`photos-ugc.l.googleusercontent.com`

**Comment by Rru247** [comment]
Another thing when i go to invidious website and watch videos through web browsers then i only see connectivity below domains.
`invidio.us`
`r3.sn-random-jhcl.googlevideo.com`
`r3.sn-random.googlevideo.com`
`redirector.gvt1.com`

**Comment by PrestonN** [comment]
This is something I wanted to look more into at the time, however with the future of Invidious being uncertain, I will be holding off on looking more into this.

You're welcome to create a new issue in the main repo about this when we are passed the initial release as I won't be focusing on this any time soon.
