### ISSUE TITLE
Localization Assistance

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#52]
Hey everyone!  I have a task that I could use help on.  This task doesn't take any programming experience and anyone with the spare time can do it.  It is a little tedious but I may as well mention it for anyone who is interested.

Localization is something that I want to add to FreeTube.  The way it typically works is that each language is split off into a JSON file with the appropriate strings to their language.  I can then use the objects within that file to display the right translations into the app.

In order for this to be done, we need an English version of this file for the rest of the translations to be based on.

There's already a start to creating this file [here](https://github.com/FreeTubeApp/FreeTube-Vue/blob/master/static/locales/en-US.json).  What I need is for the rest of the strings within FreeTube to be included in this file using the same format.  Any string of text not given from YouTube directly should be included in this file.  There are also strings within the live release of FreeTube that will likely need to be included as well.  Any string related to "Favorites" can be ignored / removed as favorites functionality will be removed within the rewrite.

Once this file is complete, I can hook it up to FreeTube and also set it up with Weblate so that translators can add their language easily to FreeTube.

There are already a couple of users who have volunteered to get started with this so if you'd like to help please join our Matrix server and we'll happily let you contribute.

The [Invidious](https://github.com/iv-org/invidious/blob/master/locales/en-US.json) locale file can also be used as a reference for what to include.

If there are any questions during this process please let me know.

**Comment by andretiagogr** [comment]
`View` and `Latest Subscriptions` are duplicated.

Is that intentional?

**Comment by PrestonN** [comment]
As of #61, we now have a filled out localization file that we can use which you can view [here](https://github.com/FreeTubeApp/FreeTube-Vue/blob/master/static/locales/en-US.yaml).  I will be actively trying to implement this file into FreeTube over the next few days.  In the mean time, we can start using this file as a base to do some translations in other languages.

The [Translation Guide](https://github.com/FreeTubeApp/FreeTube/wiki/Translations) over at the main repo is still relevant to how translations can be done here.  The only difference would be that your file will be `.yaml` instead of `.json`.

I also have access to Weblate, however it's currently hooked up to the main repo.  I will be trying to get it setup to use our new Locales files so that we can start taking advantage of Weblate for translations.  Feel free to do translations without it though if you don't want to wait.

**Comment by stevenfang1997** [comment]
I'm now doing the Chinese translation (both simplified and traditional). Will upload it to the pull request once it's finished.

**Comment by PrestonN** [comment]
Weblate is now available and ready to start accepting new translations.  If you're a translator and would like to help, please take a look at the related blog post [here](https://write.as/freetube/freetube-is-now-accepting-translations-via-weblate)

**Comment by PrestonN** [comment]
I believe we have localization structure somewhat finalized now, so this issue can be closed.
