### ISSUE TITLE
[Issue] When pressing the Pause and then Play button, a yellow square appears around the button when clicked.

### ISSUE THREAD

**Issue by OnlinePlayer865** [FreeTubeApp/FreeTube-Vue#58]
When viewing a video and then pausing the video, a yellow square appears around the pause/play button. 
Screenshot here: https://puu.sh/Ge1Rl.png. 
Pressing play to play the video does not get the yellow square to go away. 
If I pause the video by clicking in the middle of the video screen, no yellow square appears. If I then resume the video by clicking in the middle of the screen, no yellow square appears. 
I can get the yellow square to go away if I click somewhere else, like in the description. However, if I click the pause/play button again, the yellow square comes back. 

I am using Windows 10 Build 1909
Latest Commit: https://github.com/FreeTubeApp/FreeTube-Vue/commit/8576d0fddba9a3894a268e7bb6a700488f6a0a0d

Thank you.

**Comment by OnlinePlayer865** [comment]
This seems to be happening to all of the buttons in the "Now Playing" view. So this may have to do with how I'm running the app (using `npm run dev`). I don't know though. I'm not experienced in these things.

**Comment by cloudrac3r** [comment]
It's the focus indicator and it is normal for it to appear. It shows what will be clicked if you press enter on the keyboard.
