### ISSUE TITLE
New NPM Module: DASH Manifest File Generator

### ISSUE THREAD

**Issue by PrestonN** [FreeTubeApp/FreeTube-Vue#66]
One more NPM module I'd like to see created, is something that can generate the DASH Manifest files needed in order to support 1080p+ qualities within FreeTube.

Invidious already provides this file, and an example of one can be found at this link.

https://invidio.us/api/manifest/dash/jQda7atOB6I.mpd

I've had no issues downloading this file and playing it locally.

Ideally a created module would take the adaptive formats returned by [node-ytdl-core](https://github.com/fent/node-ytdl-core) and use those to create the desired manifest file.

@cloudrac3r has actually already made some progress on this with her own [Scraper API](https://git.sr.ht/~cadence/ytdi) where this functionality could likely be converted to a module.  The issue is that the files created by this API still cannot be played through a video player.

Below are example files from both services, these links will expire in 24 hours however I can refresh this however long is needed.

[Invidious Example](https://privatebin.net/?c863db134653a0c2#F9Yua3WsS1sdSKsaDufbe8C45VAcFWepN7XBgmZZNzAK)
[ytdi Example](https://privatebin.net/?e565892817ab411a#3gF2ziv9ZT3hd24N5SgukpbWmcGeMff7dqqC5vyyqn3B)

We'll need to determine the differences between the two files and what it is exactly that's preventing the ytdi version from playing.  I will try to look at this further when I have time but anyone is free to take a look at it ahead of me.

**Comment by cloudrac3r** [comment]
It's probably due to me completely making up the `index` values, but I don't know for sure if that's true.

I'm still trying to find a way to get the correct index using youtube-dl.

**Comment by omarroth** [comment]
The Invidious implementation is [here](https://github.com/iv-org/invidious/blob/62f015f/src/invidious.cr#L5102-L5220). The `indexRange` and `initRange` comes from here:
```json
"adaptiveFormats": [
    {
        "itag": 136,
        "url": "https://r2---sn-vgqs7ns7.googlevideo.com/videoplayback?expire=1596...",
        "mimeType": "video/mp4; codecs=\"avc1.4d401f\"",
        "bitrate": 899732,
        "width": 1280,
        "height": 720,
        "initRange": {
            "start": "0",
            "end": "739"
        },
        "indexRange": {
            "start": "740",
            "end": "4311"
        },
        "lastModified": "1593867805700087",
        "contentLength": "70201157",
        "quality": "hd720",
        "fps": 30,
        "qualityLabel": "720p",
        "projectionType": "RECTANGULAR",
        "averageBitrate": 358199,
        "approxDurationMs": "1567866"
    }
]
```

Both are generally required in order for playback to work properly. 

Note that livestreams and some regular videos will not have `initRange` or `indexRange`, instead there's a `dashManifestUrl` in the player response you can use instead.

**Comment by GilgusMaximus** [comment]
Still a problem, that some videos are not working out:
https://www.youtube.com/watch?v=9mRxyH0RWuQ

This video leads to a Media error in the player. However it must be observed whether this is an issue with the DASH file or whether there is a connection / server issue on Google's side. Because the error states that this is a possibility as well

**Comment by PrestonN** [comment]
The new module has been created and implemented into FreeTube, so I will be closing this issue now.
