### ISSUE TITLE
Reparsing of existing playlists and videos on channel page

### ISSUE THREAD

**Issue by GilgusMaximus** [FreeTubeApp/FreeTube-Vue#83]
When you go to a channel page, the videos and playlists are loaded and run through the scrape function from #82 . (Picture 1)
When you visit the about page of the channel and then go back to the video or playlist page, the data runs through these functions again, even tho the data was parsed already. (Picture 2)

The data could be cached easily to avoid the reload all the time and therefore run faster.

![Picture 1](https://user-images.githubusercontent.com/34301369/90690101-69a7ae00-e271-11ea-8784-392f5021792a.jpg)

![Picture 2](https://user-images.githubusercontent.com/34301369/90690131-71675280-e271-11ea-8fd7-4bb4da3cf647.jpg)

**Comment by PrestonN** [comment]
I'm having trouble duplicating this issue.  The code is using [v-show](https://github.com/FreeTubeApp/FreeTube-Vue/blob/master/src/renderer/views/Channel/Channel.vue#L76) in that section which means that it only hides the data and doesn't re-render or execute it again.  Testing with the same channel that you used isn't showing any new data printed to the console either.  I might need more information for reproduce.
